# Generated by Django 5.1 on 2024-08-27 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="vip_plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic (Free)"),
                    ("premium", "Premium"),
                    ("platinum", "Platinum"),
                ],
                default="Basic",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
