# Generated by Django 5.1 on 2024-08-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_student_teacherinfo_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='students',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
