# Generated by Django 5.1.1 on 2024-09-15 19:05

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_profile_passwordreset_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage,
                upload_to="profile_pictures/",
            ),
        ),
    ]
