# Generated by Django 5.1 on 2024-08-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
