# Generated by Django 5.1.1 on 2024-09-22 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="details",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        20, "問題內容至少要二十個字"
                    )
                ]
            ),
        ),
    ]
