# Generated by Django 5.1.1 on 2024-09-25 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_question_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuestionUserVotes",
            new_name="Votes",
        ),
        migrations.AlterField(
            model_name="question",
            name="voters",
            field=models.ManyToManyField(
                related_name="voted",
                through="questions.Votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
