# Generated by Django 5.1.1 on 2024-09-25 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_rename_questionuservotes_votes_alter_question_voters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="votes",
            unique_together={("user", "question")},
        ),
    ]
