# Generated by Django 5.1.1 on 2024-09-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_details'),
        ('questions', '0004_remove_questionuservotes_vote_value_and_more'),
    ]

    operations = [
    ]
