# Generated by Django 5.1.1 on 2024-09-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_remove_questionuservotes_vote_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="follows_count",
        ),
    ]
