# Generated by Django 5.1.1 on 2024-09-06 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="downvote",
            field=models.ManyToManyField(
                related_name="downvote", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="upvote",
            field=models.ManyToManyField(
                related_name="upvote", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
