# Generated by Django 5.1.1 on 2024-09-11 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0002_remove_answer_downvote_remove_answer_upvote_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="content",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(1, "問題描述至少要一個字")
                ]
            ),
        ),
    ]
