# Generated by Django 5.1 on 2024-09-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="groupmessage",
            old_name="created",
            new_name="created_at",
        ),
    ]
