# Generated by Django 5.1.1 on 2024-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatgroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='members_online',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
