# Generated by Django 5.1.1 on 2024-09-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatgroup_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='teacher',
        ),
    ]
