# Generated by Django 5.1.1 on 2024-09-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatgroup_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgroup",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
