# Generated by Django 5.1.1 on 2024-09-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Blog",
        ),
    ]
