# Generated by Django 5.1.1 on 2024-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_category_blog_author_blog_comments_count_blog_views_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
