# Generated by Django 5.1.1 on 2024-09-25 04:45

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage,
                upload_to="article_pictures/",
            ),
        ),
    ]
