# Generated by Django 5.1.1 on 2024-09-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0011_blog_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="cover_image",
        ),
    ]
