# Generated by Django 5.1.1 on 2024-09-17 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Appointment",
            new_name="StudentReservation",
        ),
        migrations.RenameModel(
            old_name="Schedule",
            new_name="TeacherSchedule",
        ),
    ]
