# Generated by Django 5.1.1 on 2024-09-17 16:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_teacherschedule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherschedule',
            unique_together={('teacher', 'start_time')},
        ),
    ]
