# Generated by Django 5.1.1 on 2024-09-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_alter_teacherschedule_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentreservation",
            options={"ordering": ["schedule__teacher", "schedule__start_time"]},
        ),
    ]
