# Generated by Django 5.1.1 on 2024-09-09 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_chat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='schedule',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
