# Generated by Django 5.1.1 on 2024-09-09 09:45

from django.db import migrations, models

import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0003_alter_teacher_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="expertise",
            field=models.CharField(max_length=255, validators=[teachers.models.verify]),
        ),
    ]
