# Generated by Django 5.1.1 on 2024-09-09 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='schedule',
        ),
        migrations.AddField(
            model_name='teacher',
            name='schedule_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='schedule_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
