# Generated by Django 5.1.1 on 2024-09-10 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_remove_teacher_schedule_teacher_schedule_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="schedule_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
