# Generated by Django 5.1.1 on 2024-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0006_alter_teacher_schedule_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
