# Generated by Django 5.1.1 on 2024-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_remove_teacher_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
