# Generated by Django 5.1 on 2024-08-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_question_delete_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="body",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="question",
            name="created_at",
        ),
    ]
