# Generated by Django 5.1.1 on 2024-09-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_clicked_notification_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="question",
        ),
        migrations.AddField(
            model_name="notification",
            name="question_id",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
