# Generated by Django 5.1.1 on 2024-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_remove_notification_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="answer_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notification",
            name="question_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
